import type { Metadata } from 'next';

import Providers from '../providers/Providers';

import './global.css';
import '@/styles/main.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
        <Providers>
          <header>Page header</header>
          <main>{children}</main>
          <footer>Page footer</footer>
        </Providers>
      </body>
    </html>
  );
}
